### ISSUE TITLE
Error: uninitialized constant User (NameError)

### ISSUE THREAD

**Issue by sandrojca** [SCPR/secretary-rails#15]
rails generate secretary:install
/home/sandro/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:261:in `const_get': uninitialized constant User (NameError)
	from /home/sandro/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:261:in `block in constantize'

**Comment by Ravenstine** [comment]
I think that Secretary needs a user model when running the install generator.  If you don't have one, make one or, if you already have one but it is not called `User`(e.g. Member), you can add something like this to your `config/application.rb`:

```ruby
Secretary.configure do |config|
  config.user_class = "::Member"
end
```

**Comment by bricker** [comment]
Hi @sandrojca — Sorry the documentation isn't very clear on setting up a User class.

By default Secretary assumes you'll have a `User` class in your application. If the class for your users is named something else, you can change it in configuration (https://github.com/SCPR/secretary-rails#configuration). Currently there isn't a way to disable user tracking, but that would be a very easy update to make if you need it.

**Comment by bricker** [comment]
Oops thanks @Ravenstine, I missed your comment by just a second :+1:
